# build stage
FROM mcr.microsoft.com/dotnet/sdk:5.0 as builder

WORKDIR /src
COPY src/ .

USER ContainerAdministrator
RUN dotnet restore && dotnet publish

# final image stage
FROM mcr.microsoft.com/dotnet/runtime:5.0

WORKDIR /dotnetapp
COPY --from=builder ./src/bin/Debug/net5.0/publish .

CMD ["dotnet", "HelloWorld.NetCore.dll"]